name: wealth_flow
version: '1.0.0'
config-version: 2
profile: wealth_flow

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  wealth_flow:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  wealth_flow:
    +schema: silver
